#!/usr/bin/env bash
# Per-app OOM bias setup. Runs as the user (no sudo).
#
# Two mechanisms, both opt-in via `evn install systemd`:
#
# 1. User-level .desktop overrides in $XDG_DATA_HOME/applications/.
#    Each override re-launches the app through launchers/oom-launch.sh,
#    which wraps the original binary in a systemd transient scope carrying
#    explicit OOM properties:
#      * heavy / "kill me first" apps  -> OOMScoreAdjust=+500
#          (kernel-OOM safety net; systemd-oomd already prefers them by usage)
#      * fragile apps we want to spare -> OOMScoreAdjust=-500
#                                       + ManagedOOMPreference=avoid
#          ('avoid' deprioritises but does NOT immortalise: if the protected
#           app is itself the actual runaway, oomd will still kill it. That
#           is by design — keeps the laptop from freezing.)
#
# 2. User-level systemd drop-ins for D-Bus activated terminal services
#    whose actual processes do NOT live under the .desktop launcher's
#    transient scope (gnome-terminal-server is the canonical example —
#    the .desktop binary just sends a D-Bus call and exits, the window
#    runs inside the existing service). Those need a service-level
#    ManagedOOMPreference=avoid drop-in; the .desktop wrap-around alone
#    does nothing for them.
#
# Customisation:
#   Drop a file at $EVANGELIST/custom/oom-priorities.list with one tuple
#   per line in the format
#         <basename>:<oom-score>:<managed-oom-preference>
#   to add new apps or override defaults. Lines starting with '#' are
#   ignored. The last tuple sharing a basename wins.
#
# Idempotent. Use `evn uninstall` (or remove the marker-tagged files by
# hand) to revert.

set -uo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
LAUNCHER="$SCRIPT_DIR/launchers/oom-launch.sh"
USER_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
USER_SYSD="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
MARKER='# Generated by evangelist (oom-priority)'

SEARCH_DIRS=(
  /usr/local/share/applications
  /usr/share/applications
  /var/lib/snapd/desktop/applications
  /var/lib/flatpak/exports/share/applications
  "${XDG_DATA_HOME:-$HOME/.local/share}/flatpak/exports/share/applications"
)

## tuples: <basename>:<oom-score>:<managed-oom-preference>
##   <managed-oom-preference> is one of: none|avoid|omit
##   - 'avoid' deprioritises (still killable as a last resort)
##   - 'omit'  = never killed by oomd (NOT recommended for terminals — can
##              freeze the laptop if the terminal itself goes runaway)
##
## Multiple basenames per logical app cover the deb / snap / flatpak
## variants since the .desktop filename varies. The first hit in
## SEARCH_DIRS wins; missing apps are silently skipped.
APPS=(
  ## --- Heavy targets — pushed up the kernel-OOM kill order. ----------------
  slack_slack:500:none
  slack:500:none
  spotify_spotify:500:none
  spotify:500:none
  telegram-desktop_telegram-desktop:500:none
  org.telegram.desktop:500:none
  google-chrome:500:none
  com.google.Chrome:500:none
  chromium_chromium:500:none

  ## --- Protected terminals — oomd actively skips these scopes. -------------
  ## NOTE: gnome-terminal launches via D-Bus and the actual processes live
  ## inside gnome-terminal-server.service. The .desktop wrap-around alone
  ## does NOT protect those — the user-level systemd drop-in below does.
  kitty:-500:avoid
  Alacritty:-500:avoid
  alacritty:-500:avoid
  org.wezfurlong.wezterm:-500:avoid
  com.gexperts.Tilix:-500:avoid
  terminator:-500:avoid
  foot:-500:avoid
  org.gnome.Terminal:-500:avoid
)

## D-Bus activated terminal services that need a service-level drop-in.
DBUS_TERMINAL_SERVICES=(
  gnome-terminal-server.service
)

## Pull in user customisations. Append semantics: later tuples for the
## same basename overwrite earlier ones because the loop below writes
## $USER_DIR/<basename>.desktop and the last write wins.
USER_CONF="${EVANGELIST:-$PWD}/custom/oom-priorities.list"
if [[ -f "$USER_CONF" ]]; then
  while IFS= read -r line; do
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    APPS+=("$line")
  done <"$USER_CONF"
  echo "loaded custom: $USER_CONF"
fi

[[ -x "$LAUNCHER" ]] || chmod +x "$LAUNCHER"
mkdir -p "$USER_DIR" "$USER_SYSD"

find_desktop() {
  local name=$1 dir
  for dir in "${SEARCH_DIRS[@]}"; do
    [[ -f "$dir/$name.desktop" ]] && {
      echo "$dir/$name.desktop"
      return 0
    }
  done
  return 1
}

write_override() {
  local src=$1 score=$2 pref=$3 dst=$4
  ## awk only rewrites Exec= in [Desktop Entry]. Lines under
  ## [Desktop Action <name>] are passed through untouched, so right-click
  ## actions like "New Window" / "-quit" / "-incognito" keep working.
  awk -v marker="$MARKER" -v launcher="$LAUNCHER" -v score="$score" -v pref="$pref" '
    BEGIN { print marker; section = "" }
    /^\[.*\]/ { section = $0; print; next }
    /^Exec=/ {
      if (section == "[Desktop Entry]") {
        sub(/^Exec=/, "")
        printf "Exec=%s %s %s -- %s\n", launcher, score, pref, $0
      } else {
        print
      }
      next
    }
    { print }
  ' "$src" >"$dst.tmp" && mv "$dst.tmp" "$dst"
}

write_user_oomd_drop_in() {
  local service=$1 dir="$USER_SYSD/$service.d"
  mkdir -p "$dir"
  cat >"$dir/10-oomd.conf" <<EOF
$MARKER
[Service]
ManagedOOMPreference=avoid
EOF
}

## ---- 1. .desktop overrides ----------------------------------------------
written=0
skipped=0
for tuple in "${APPS[@]}"; do
  IFS=: read -r name score pref <<<"$tuple"
  if src=$(find_desktop "$name"); then
    dst="$USER_DIR/$name.desktop"
    write_override "$src" "$score" "$pref" "$dst"
    echo "  [+] $name (score=$score pref=$pref) -> $dst"
    written=$((written + 1))
  else
    skipped=$((skipped + 1))
  fi
done

if ((written > 0)) && command -v update-desktop-database >/dev/null; then
  update-desktop-database "$USER_DIR" 2>/dev/null || :
fi
echo "wrote $written .desktop override(s); $skipped not installed (skipped)."

## ---- 2. user-level systemd drop-ins for D-Bus activated terminals -------
sysd_written=0
for service in "${DBUS_TERMINAL_SERVICES[@]}"; do
  if systemctl --user cat "$service" &>/dev/null; then
    write_user_oomd_drop_in "$service"
    echo "  [+] $service -> $USER_SYSD/$service.d/10-oomd.conf (avoid)"
    sysd_written=$((sysd_written + 1))
  fi
done

if ((sysd_written > 0)); then
  systemctl --user daemon-reload
  echo "wrote $sysd_written user-level systemd drop-in(s); ran systemctl --user daemon-reload."
fi
