# .:!:. >SED-UPDATE .:!:.

## aspell (used by vim spell checker)
export ASPELL_CONF="per-conf $XDG_CONFIG_HOME/aspell/aspell.conf; \
    personal $XDG_CONFIG_HOME/aspell/en.pws; \
    repl $XDG_CONFIG_HOME/aspell/en.prepl"

## nvim
if which nvim &> /dev/null
then
  VISUAL=nvim
elif which vim &> /dev/null
then
  VISUAL=vim
fi

export VISUAL
export EDITOR=$VISUAL

## Finish configuring locales.
if [[ -z $LANG ]]
then
  if locale -a | grep -qi 'en_us.utf8'
  then
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
  else
    echo "No utf8 locales found. See 'locale-gen'."
  fi
fi

## grep
## set the color of 'file name' section in grep's output
## fn=33 (default is 35); 33 is more visible on a white background of
## transparent dark terminal window.
export GREP_COLORS='ms=01;31:mc=01;31:sl=:cx=:fn=33:ln=32:bn=32:se=36'

## Set initialization file for Vim
if ! which nvim &> /dev/null && which vim &> /dev/null \
  && grep -qE '^n?vim' "$EVANGELIST/.update-list"
then
  export MYVIMRC="$XDG_CONFIG_HOME/nvim/init.vim"
  export VIMINIT=":source $MYVIMRC"
fi

# .:!:. <SED-UPDATE .:!:.
