# XDG base directory setup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# ZSH
export ZDOTDIR="$HOME/.config/zsh"
export ZPLUG_HOME="$XDG_DATA_HOME/zplug"
export ZPLUG_CACHE_DIR="$XDG_CACHE_HOME/zplug"
export HISTFILE="$XDG_DATA_HOME/zsh_history"
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE

# texlive
export PATH="$PATH:/usr/local/texlive/2020/bin/x86_64-linux"

# golang
export PATH="$PATH:/usr/local/go/bin"
export GOPATH="$HOME/Miscellanea/TestLab/go"

# aspell (used by vim spell checker ?)
export ASPELL_CONF="per-conf $XDG_CONFIG_HOME/aspell/aspell.conf; \
    personal $XDG_CONFIG_HOME/aspell/en.pws; \
    repl $XDG_CONFIG_HOME/aspell/en.prepl"

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export SINGULARITY_CACHEDIR="$XDG_CACHE_HOME/singularity"

# ipython/jupyter
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

# less, wget, libice
export LESSHISTFILE=-
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"

# nvim
export VISUAL=nvim
export EDITOR="$VISUAL"

# grep
## set the color of 'file name' section in grep's output
## fn=33 (default is 35); 33 is better visible on a white background of
## transparent dark terminal window.
export GREP_COLORS='ms=01;31:mc=01;31:sl=:cx=:fn=33:ln=32:bn=32:se=36'
