# The sourcing below might fail for IDEs.
# If this is the case, you will need to expand $ZPLUG_HOME variable.
source "$ZPLUG_HOME/init.zsh"

zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:3
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug 'zsh-users/zsh-completions', depth:1

AGKOZAK_MULTILINE=0
AGKOZAK_PROMPT_CHAR=( '>' '>' ':' )
AGKOZAK_VIRTUALENV_CHARS=( '' '' )

AGKOZAK_COLORS_PATH=white
AGKOZAK_COLORS_USER_HOST=yellow
AGKOZAK_COLORS_BRANCH_STATUS=red
AGKOZAK_COLORS_VIRTUALENV=blue
AGKOZAK_COLORS_PROMPT_CHAR=white
zplug 'agkozak/agkozak-zsh-theme'

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load
source $ZDOTDIR/extra.zsh
