# The sourcing below might fail for IDEs.
# If this is the case, you will need to expand $ZPLUG_HOME variable.
source "$ZPLUG_HOME/init.zsh"

zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:3
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug 'zsh-users/zsh-completions', depth:1

# THEME
## If you don't face any bugs,
## (particularly the one related to resizing terminal window)
## powerlevel10k is a good choice.
# zplug 'romkatv/powerlevel10k', as:theme, depth:1
## Otherwise, you can use minimalistic 'agkozak' theme.
zplug 'agkozak/agkozak-zsh-theme'
[[ -n $(zplug list | grep agkozak) ]] && source $ZDOTDIR/agkozakrc

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load
source $ZDOTDIR/extra.zsh
source $EVANGELIST/bash/aliases-functions.sh

# Import user-defined settings
[[ -f $EVANGELIST/custom/custom.zsh ]] \
  && source $EVANGELIST/custom/custom.zsh

# if the system has both Vim and Neovim, use the latter
which nvim &> /dev/null && which vim &> /dev/null && alias vim=nvim

