## Even if you don't care about your $HOME tidiness,
## which is the primary goal of these variable definitions,
## other files require them to be defined.

# Set initialization file for Vim
if ! which nvim &> /dev/null && which vim &> /dev/null
then
  export MYVIMRC=$XDG_CONFIG_HOME/nvim/init.vim
  export VIMINIT=":source $MYVIMRC"
fi

# Finish configuring locales.
if [[ -z $LANG ]] && locale -a | grep -qi 'en_us.utf8'
then
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
else
  echo "No utf8 locales found. See 'local-gen'"
fi

if which nvim &> /dev/null
then
  VISUAL=nvim
elif which vim &> /dev/null
then
  VISUAL=vim
fi

export VISUAL
export EDITOR=$VISUAL


# Standard bash settings
## Don't put duplicate lines in the history. See bash(1) for more options
## ... or force ignoredups and ignorespace.
HISTCONTROL=ignoredups:ignorespace

## Append to the history file, don't overwrite it.
shopt -s histappend

## For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

## Check the window size after each command and, if necessary,
## Update the values of LINES and COLUMNS.
shopt -s checkwinsize


# Set minimalist prompt.
## \\[\e[1;32m\\] - color begins (1;32 - bold green)
## \\[\e[m\\] - color ends
## \u - username
## \W - current workdir
PS1="\\[\e[1;32m\\]\u \\[\e[1;37m\\]\W\\[\e[m\\]$ "

# Colored output for basic commands.
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'  # same as grep -F
alias egrep='egrep --color=auto'  # same as grep -E

# Handy aliases
alias l='ls -lAh'
alias ll='ls -lAht'
alias fd='find . -type d -name'
alias ff='find . -type f -name'
alias md='mkdir -p'
alias bashrc='vim ~/.bashrc'

# if the system has both Vim and Neovim, use the latter
which nvim &> /dev/null && which vim &> /dev/null && alias vim=nvim

# Increase key repeat rate with xset if it is available.
# Ignore "unable to open display" error that appears in docker.
which xset &> /dev/null && xset r rate 250 70 2> /dev/null
